#!/bin/sh

# All code courtesy of https://github.com/rayes0/scripts/tree/main/cutefetch
# I only modified it to suit my needs.

LC_ALL=C
LANG=C

# System Info
os() {
	if [ -f /etc/os-release ]; then
    		. /etc/os-release
    		OS=$NAME
    		OS="${OS%Linux}"
		echo $OS
	fi
}
wm() {
	xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep "WM_NAME" | cut -f2 -d \"
}
shell() {
	basename ${SHELL}
}
kernel() {
	uname -r | sed 's/-arch.*//'
}


# Colors and formatting
n=$'\033[0m' # Normal text

b=""
l=""
s=""
[ "${CF_BOLD:-true}" = 'true' ] && b=$'\033[1m' # Bold text
[ "${CF_ITALIC:-false}" = 'true' ] && l=$'\033[3m' # Italic text
[ "${CF_ITALIC_LABELS:-false}" = 'true' ] && s=$'\033[3m' # Label Italic text

c=3 cb=4
for j in c cb; do
	for i in {0..7}; do
		printf -v $j$i %b "\033[${!j}${i}m"
	done
done

cmd='cat'

owl() {
	$cmd <<-EOF
	      ${c4}.___,       
	   ${c3}___(${n}'${c3}v${n}'${c3})___    
	   ${c2}\`"-\\${n}._.${c2}/-"'    
	       ${c4}^ ^$n
	   $c2${b}$s OS$n  ${l}$(os)$n
	   $c4${b}$s KR$n  ${l}$(kernel)$n  
	   $c3${b}$s WM$n  ${l}$(wm)$n
	   $c5${b}$s SH$n  ${l}$(shell)$n
	   
	EOF
}

# Parse arguments and run functions
${CF_DEFAULT_ANIMAL:-owl} && exit 0
